name: Configure Vault server
on: workflow_dispatch
jobs:
  configure_vault_server:
    name: Configure Vault Server
    runs-on: ubuntu-latest
    steps:

      - name: cd to Ansible directory
        run: cd Ansible/

      - name: ls
        run: ls
        
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: Ansible/playbook.yml
          inventory: Ansible/.hosts
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          user: azureuser
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'