name: Configure Vault server
on: workflow_dispatch
jobs:
  configure_vault_server:
    name: Configure Vault Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Ansible
    steps:
    
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: ./playbook.yml
          inventory: ./.hosts
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          user: azureuser