name: Deploy infrastructure with Terraform
on: workflow_dispatch
jobs:
  deploy_infrastructure:
    name: Deploy infrastructure
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AD_SP_CREDS }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
  
      - name: Call terraform output
        run: |
          output=$(terraform output test)
          echo $output