name: Configure Vault server
on: workflow_dispatch
jobs:
  configure_vault_server:
    name: Configure Vault Server
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: Ansible/
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory .hosts
            --verbose